version: '3.8'

services:
  swd-api:
    image: swd-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

      # Gmail SMTP Configuration
      - EMAIL_FROM=caohuutritl1234@gmail.com
      - EMAIL_FROM_NAME=Smart Weather Data Lab
      - EMAIL_APP_PASSWORD=jekvdpbmlqkwjbpf

    restart: always
